### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by SvenMeierhans**
Update composer.json for Contao 4 compatibility.

### CODE REVIEW

**Comment by backbone87** [comment]
Did you test the extension with Contao 4?

**Comment by SvenMeierhans** [comment]
Yes. So far, it's working as intended. But I couldn't validate all of the features yet.

**Comment by davidmaack** [comment]
Yepp, seem to work :)

**Comment by frontendschlampe** [comment]
it's already done

**Pull request closed without merging**
